# Generated by Django 3.2.3 on 2021-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=2, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
